# Generated by Django 3.2.9 on 2021-11-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['-creado']},
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='updated_at',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='completed',
            new_name='completada',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='created_at',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='title',
            new_name='titulo',
        ),
    ]
